var categories = 
[
    {
        name: "bank", 
        icon: "/img/category/bank/default.png",
        groups: 
        [
            {
                name: "Aareal Bank",
                domains: 
                [
                    "aareal.com",                
                    "aareal-bank.com",
                ]
            },
            {
                name: "ABI Bank",
                domains:
                [
                    "abi.al",
                ]
            },
            {
                name: "АБСОЛЮТБАНК (Absolutbank)",
                domains:
                [
                    "absolutbank.by",
                ]
            },
            {
                name: "AccessBank",
                domains:
                [
                    "accessbank.az",
                    "myaccess.az",
                ]
            },
            {
                name: "AFB Bank ASC",
                domains:
                [
                    "afb.az",
                ]
            },
            {
                name: "Aion Bank",
                domains:
                [
                    "aion.be",
                ]
            },
            {
                name: "Альфа-Банк (Alfa-Bank)",
                domains:
                [
                    "alfa-biz.by",
                    "alfabank.by",
                ]
            },
            {
                name: "Alior Bank",
                domains:
                [
                    "aliorbank.pl",
                    "t-mobilebankowe.pl",
                ]
            },
            {
                name: "Allianz",
                domains:
                [
                    "allianzinvest.at",
                ]
            },
            {
                name: "AlpenBank",
                domains:
                [
                    "alpenbank.com",
                ]
            },
            {
                name: "ALPHA BANK",
                domains:
                [
                    "alphabank.al",
                ]
            },
            {
                name: "Ameriabank",
                domains:
                [
                    "ameriabank.am",
                ]
            },
            {
                name: "American Express",
                domains:
                [
                    "americanexpress.com",
                ]
            },
            {
                name: "Andbank",
                domains:
                [
                    "andbank.com",
                    "andbank.com.br",
                    "inversis.com",
                ]
            },
            {
                name: "APO - Österreichische Ärzte & Apotheker Bank AG",
                domains:
                [
                    "apobank.at",
                ]
            },
            {
                name: "Araratbank",
                domains:
                [
                    "araratbank.am",
                ]
            },
            {
                name: "Ardshinbank",
                domains:
                [
                    "ardshinbank.am",
                ]
            },
            {
                name: "Argenta",
                domains:
                [
                    "argenta.be",
                ]
            },
            {
                name: "Armbusinessbank",
                domains:
                [
                    "armbusinessbank.am",
                ]
            },
            {
                name: "Armeconombank",
                domains:
                [
                    "aeb.am",
                ]
            },
            {
                name: "ArmedForcesBank",
                domains:
                [
                    "afbank.com",
                ]
            },
            {
                name: "ArmSwissbank",
                domains:
                [
                    "armswissbank.am",
                ]
            },
            {
                name: "Artsakhbank",
                domains:
                [
                    "artsakhbank.am",
                    "artsakhbank.com",
                ]
            },
            {
                name: "ASB Bank",
                domains:
                [
                    "asb.az",
                    "asb.co.nz",
                ]
            },
            {
                name: "AtaBank",
                domains:
                [
                    "atabank.com",
                ]
            },
            {
                name: "Attijariwafa bank",
                domains:
                [
                    "attijaribank.mr",
                    "attijariwafa.com",
                    "attijariwafa.com.eg",
                    "attijariwafabank.com",
                    "attijariwafabank-europe.fr",
                    "biat.tg",
                    "creditducongo.com",
                    "creditdusenegal.com",
                    "e-attijari.com",
                    "sib.ci",
                    "ugb-ebank.ga",
                    "webank.com.tn",
                ]
            },
            {
                name: "Austrian Anadi Bank AG",
                domains:
                [
                    "anadibank.com",
                ]
            },
            {
                name: "AWS - Austria Wirtschaftsservice",
                domains:
                [
                    "aws.at",
                ]
            },
            {
                name: "AXA Bank",
                domains:
                [
                    "axabank.be",
                ]
            },
            {
                name: "Azərbaycan Beynəlxalq Bankı",
                domains:
                [
                    "ibar.az",
                ]
            },
            {
                name: "AZkreditbank",
                domains:
                [
                    "azkreditbank.com",
                ]
            },
            {
                name: "Banking Austria",
                domains:
                [
                    "banking.co.at",
                ]
            },
            {
                name: "Bank Avrasiya",
                domains:
                [
                    "bankavrasiya.az",
                ]
            },
            {
                name: "Bank BPH",
                domains:
                [
                    "bph.pl",
                ]
            },
            {
                name: "Банк Дабрабыт (Bank Dobrabyt)",
                domains:
                [
                    "bankdabrabyt.by",
                ]
            },
            {
                name: "Bank Gutmann",
                domains:
                [
                    "gutmann.at",
                ]
            },
            {
                name: "Bankhaus Krentschker & Co. AG",
                domains:
                [
                    "krentschker.at",
                ]
            },
            {
                name: "Bankhaus Schelhammer & Schattera",
                domains:
                [
                    "schelhammer.at",
                ]
            },
            {
                name: "Bankhaus Spängler",
                domains:
                [
                    "spaengler.at",
                ]
            },
            {
                name: "bank mellat",
                domains:
                [
                    "bankmellat.ir",
                ]
            },
            {
                name: "Bank Melli Iran",
                domains:
                [
                    "bmi.ir",
                ]
            },
            {
                name: "Bank Millenium",
                domains:
                [
                    "bankmillennium.pl",
                ]
            },
            {
                name: "Bank Nowy BGF S.A.",
                domains:
                [
                    "pbsbank.pl",
                ]
            },
            {
                name: "Banco do Brasil",
                domains:
                [
                    "bancobrasil.com.br",
                    "bb.com.br",
                ]
            },
            {
                name: "BancSabadell d'Andorra",
                domains:
                [
                    "bsandorra.com",
                ]
            },
            {
                name: "BANK OF CHINA",
                domains:
                [
                    "bankofchina.com",
                ]
            },
            {
                name: "Bank Pekao",
                domains:
                [
                    "cdm24.pl",
                    "pekao.com.pl",
                    "pekao24.pl",
                    "pekaobiznes24.pl",
                    "pekaobh.pl",
                ]
            },
            {
                name: "Bank Pocztowy",
                domains:
                [
                    "envelobank.pl",
                    "pocztowy.pl",
                    "pocztowy24.pl",
                ]
            },
            {
                name: "Банк РРБ (Bank RRB)",
                domains:
                [
                    "rrb.by",
                ]
            },
            {
                name: "Bank Winter",
                domains:
                [
                    "bankwinter.com",
                ]
            },
            {
                name: "Banque Eni",
                domains:
                [
                    "banqueenisa.be",
                    "eni.com",
                    "eni.it",
                ]
            },
            {
                name: "Banque Transatlantique",
                domains:
                [
                    "banquetransatlantique.be",
                    "banquetransatlantique.co.uk",
                    "banquetransatlantique.com",
                    "banquetransatlantique.lu",
                ]
            },
            {
                name: "BAWAG P.S.K.",
                domains:
                [
                    "bawagpsk.com",
                ]
            },
            {
                name: "BBVA",
                domains:
                [
                    "bbva.be",
                    "bbva.ch",
                    "bbva.com",
                    "bbva.com.ar",
                    "bbva.com.co",
                    "bbva.com.py",
                    "bbva.com.uy",
                    "bbva.es",
                    "bbva.fr",
                    "bbva.mx",
                    "bbva.pe",
                    "bbva.pt",
                    "bbvanetcash.co.uk",
                    "bbvauk.com",
                    "bbvausa.com",
                    "provincial.com",
                ]
            },
            {
                name: "Белагропромбанк (Belagroprombank)",
                domains:
                [
                    "belapb.by",
                ]
            },
            {
                name: "Беларусбанк (Belarusbank)",
                domains:
                [
                    "belarusbank.by",
                ]
            },
            {
                name: "Белорусский народный банк (Belarusky Narodny Bank)",
                domains:
                [
                    "bnb.by",
                    "imbanking.by",
                ]
            },
            {
                name: "Belfius",
                domains:
                [
                    "belfius.be",
                ]
            },
            {
                name: "Белгазпромбанк (Belgazprombank)",
                domains:
                [
                    "belgazprombank.by",
                    "bgpb.by",
                    "e-bgpb.by",
                ]
            },
            {
                name: "Белинвестбанк (Belinvestbank)",
                domains:
                [
                    "belinvestbank.by",
                ]
            },
            {
                name: "Beobank",
                domains:
                [
                    "beobank.be",
                ]
            },
            {
                name: "BGK",
                domains:
                [
                    "bgk.pl",
                    "bgk24.pl",
                ]
            },
            {
                name: "BKS Bank",
                domains:
                [
                    "bks.at",
                    "bksbank-online.at",
                ]
            },
            {
                name: "BKT",
                domains:
                [
                    "bkt.com.al",
                ]
            },
            {
                name: "BNP PARIBAS",
                domains:
                [
                    "bnpparibas.com",
                    "bnpparibas.pl",
                    "bnpparibasfortis.be",
                    "bnpparibasfortis.com",
                    "group.bnpparibas",
                    "webmakler.pl",
                ]
            },
            {
                name: "BOŚ Bank",
                domains:
                [
                    "bosbank.pl",
                    "bosbank24.pl",
                    "iboss24.pl",
                ]
            },
            {
                name: "BPA - Banca Privada d'Andorra",
                domains:
                [
                    "bpa.ad",
                ]
            },
            {
                name: "bpost banque",
                domains:
                [
                    "bpostbanque.be",
                ]
            },
            {
                name: "БПС-Сбербанк (BPS-Sberbank)",
                domains:
                [
                    "bps-sberbank.by",
                ]
            },
            {
                name: "БСБ Банк (BSB Bank)",
                domains:
                [
                    "bsb.by",
                ]
            },
            {
                name: "БТА Банк (BTA Bank)",
                domains:
                [
                    "bta.by",
                    "btabank.by",
                ]
            },
            {
                name: "BTV - Bank für Tirol und Vorarlberg",
                domains:
                [
                    "btv.at",
                    "btv-bank.ch",
                    "btv-bank.de",
                    "btv3banken.ch",
                    "meinebtv.at",
                ]
            },
            {
                name: "Byblos Bank",
                domains:
                [
                    "byblosbank.com",
                    "byblosbankarmenia.am",
                    "byblosonline.com",
                ]
            },
            {
                name: "CaixaBank",
                domains:
                [
                    "caixabank.pl",
                    "lacaixa.pl",
                ]
            },
            {
                name: "Capital Bank - GRAWE Gruppe AG",
                domains:
                [
                    "capitalbank.at",
                ]
            },
            {
                name: "China Construction Bank",
                domains:
                [
                    "ccb.com",
                ]
            },
            {
                name: "Citibank",
                domains:
                [
                    "citi.com",
                    "citi.eu",
                    "citibank.co.uk",
                    "citibank.com",
                    "citigroup.com",
                ]
            },
            {
                name: "Citi Handlowy",
                domains:
                [
                    "citibank.pl",
                    "citibankonline.pl",
                    "citidirect.com",
                    "dmbh.pl",
                ]
            },
            {
                name: "Commerzbank AG",
                domains:
                [
                    "commerzbank.ae",
                    "commerzbank.at",
                    "commerzbank.be",
                    "commerzbank.ch",
                    "commerzbank.cn",
                    "commerzbank.co.uk",
                    "commerzbank.com",
                    "commerzbank.com.br",
                    "commerzbank.cz",
                    "commerzbank.es",
                    "commerzbank.fr",
                    "commerzbank.hu",
                    "commerzbank.it",
                    "commerzbank.jp",
                    "commerzbank.nl",
                    "commerzbank.ru",
                    "commerzbank.sk",
                    "commerzbank.us",
                ]
            },
            {
                name: "ConverseBank",
                domains:
                [
                    "conversebank.am",
                ]
            },
            {
                name: "Credins Bank",
                domains:
                [
                    "bankacredins.com",
                ]
            },
            {
                name: "CREDIT BANK OF ALBANIA",
                domains:
                [
                    "creditbankofalbania.al",
                ]
            },
            {
                name: "Crédit Agricole",
                domains:
                [
                    "acba.am",
                    "acbadigital.am",
                    "credit-agricole.pl",
                ]
            },
            {
                name: "Crédit Andorra",
                domains:
                [
                    "e-credit.ad",
                ]
            },
            {
                name: "Crelan",
                domains:
                [
                    "crelan.be",
                ]
            },
            {
                name: "Danske Bank",
                domains:
                [
                    "bv-corporatebanking.de",
                    "danskebank.co.uk",
                    "danskebank.com",
                    "danskebank.dk",
                    "danskebank.fi",
                    "danskebank.ie",
                    "danskebank.no",
                    "danskebank.pl",
                    "danskebank.se",
                    "danskeci.com",
                ]
            },
            {
                name: "Degroof Petercam",
                domains:
                [
                    "degroofpetercam.be",
                    "degroofpetercam.com",
                ]
            },
            {
                name: "Delta Lloyd Bank",
                domains:
                [
                    "deltalloydbank.com",
                ]
            },
            {
                name: "DemirBank",
                domains:
                [
                    "demirbank.kg",
                ]
            },
            {
                name: "DenizBank",
                domains:
                [
                    "denizbank.com",
                ]
            },
            {
                name: "Deutsche Bank",
                domains:
                [
                    "db.com",
                    "deutsche-oppenheim.de",
                    "deutschebank.com",
                    "oppenheim.de",
                    "oppenheimbank.com",
                ]
            },
            {
                name: "DNB Bank Polska S.A.",
                domains:
                [
                    "dnb.pl",
                    "dnbon.pl",
                ]
            },
            {
                name: "easybank",
                domains:
                [
                    "easybank.at",
                ]
            },
            {
                name: "ERSTE Group",
                domains:
                [
                    "24banking.md",
                    "24banking.ro",
                    "bcr.md",
                    "bcr.ro",
                    "business24.cz",
                    "csas.cz",
                    "ebb4all.com",
                    "erstebank.hr",
                    "erstebank.hu",
                    "erstebank.me",
                    "erstebank.rs",
                    "erstegroup.com",
                    "ersteinvestment.hu",
                    "ersteprivatebanking.at",
                    "ersteprivatebanking.com",
                    "ersteprivatebanking.cz",
                    "ersteprivatebanking.hr",
                    "ersteprivatebanking.hu",
                    "ersteprivatebanking.ro",
                    "ersteprivatebanking.sk",
                    "infocont.md",
                    "netbanking.mk",
                    "servis24.cz",
                    "slsp.sk",
                    "sparkasse.at",
                    "sparkasse.ba",
                    "sparkasse.mk",
                    "sparkasse.si",
                ]
            },
            {
                name: "ΕΤΕ - Αρχική Σελίδα",
                domains:
                [
                    "nbg.gr",
                ]
            },
            {
                name: "Euroclear",
                domains:
                [
                    "euroclear.com",
                ]
            },
            {
                name: "Europabank",
                domains:
                [
                    "europabank.be",
                    "ebonline.be",
                ]
            },
            {
                name: "evocaBank",
                domains:
                [
                    "evocabank.am",
                ]
            },
            {
                name: "Expressbank",
                domains:
                [
                    "express24.az",
                    "expressbank.az",
                ]
            },
            {
                name: "FactorBank",
                domains:
                [
                    "factorbank.com",
                ]
            },
            {
                name: "FCA Bank",
                domains:
                [
                    "fcaautomotiveservices.co.uk",
                    "fcabank.at",
                    "fcabank.be",
                    "fcabank.de",
                    "fcabank.gr",
                    "fcabank.it",
                    "fcabank.pl",
                    "fcabankgroup.com",
                    "fcacapital.ch",
                    "fcacapital.dk",
                    "fcacapital.es",
                    "fcacapital.fr",
                    "fcacapital.nl",
                    "fcacapital.pt",
                    "fcagroup.com",
                    "leasys.com",
                ]
            },
            {
                name: "FCE Bank - Ford Credit",
                domains:
                [
                    "fcebank.com",
                    "fcebank.pl",
                    "ford.pl",
                ]
            },
            {
                name: "Fibank - Cilësia  vjen e para",
                domains:
                [
                    "fibank.al",
                ]
            },
            {
                name: "Франсабанк (Fransabank)",
                domains:
                [
                    "fransabank.by",
                ]
            },
            {
                name: "Generali Bank",
                domains:
                [
                    "generalibank.at",
                ]
            },
            {
                name: "Getin Bank",
                domains:
                [
                    "getinbank.pl",
                    "gnb.pl",
                ]
            },
            {
                name: "Grupa BPS",
                domains:
                [
                    "absbank.pl",
                    "absbank24.pl",
                    "augustow.pl",
                    "bank-konopiska.pl",
                    "bank-wbs.pl",
                    "bankbbs.pl",
                    "bankbialopole.pl",
                    "bankbps.pl",
                    "bankbsilawa.pl",
                    "banklbs.pl",
                    "bankmbs.pl",
                    "banksp.pl",
                    "bbsustrzyki.pl",
                    "bs.cieszyn.pl",
                    "bs.gorlice.pl",
                    "bs.limanowa.pl",
                    "bs.ostrowiec.pl",
                    "bs.piwniczna.pl",
                    "bs.rzeszow.pl",
                    "bs.stalowa-wola.pl",
                    "bs.stary.sacz.pl",
                    "bs.ustron.pl",
                    "bs.wegierskagorka.pl",
                    "bs-aleksandrow.pl",
                    "bs-andrespol.pl",
                    "bs-blazowa.pl",
                    "bs-brzesko.pl",
                    "bs-chojnow.pl",
                    "bs-gilowice.pl",
                    "bs-jawor.pl",
                    "bs-kolbuszowa.pl",
                    "bs-krzeszowice.pl",
                    "bs-opole.com.pl",
                    "bs-opole.pl",
                    "bs-ozorkow.pl",
                    "bs-sedziszow.pl",
                    "bs-slomniki.com.pl",
                    "bs-sokolka.pl",
                    "bs-suchedniow.com.pl",
                    "bs-swierklaniec.pl",
                    "bs-warta.pl",
                    "bs-wloszczowa.com.pl",
                    "bs-wolbrom.com.pl",
                    "bs-wolbrom.pl",
                    "bs-zabkowicesl.pl",
                    "bs-zawadzkie.pl",
                    "bs-zywiec.pl",
                    "bsadamow.pl",                   
                    "bsbank.com.pl",
                    "bsbarcin.pl",
                    "bsbarglow.pl",
                    "bsbartoszyce.com.pl",
                    "bsbiala.pl",
                    "bsbialapodlaska.pl",
                    "bsbiecz.pl",
                    "bsbiecz24.pl",
                    "bsbielsk.pl",
                    "bsbilgoraj.pl",
                    "bsbiszcza.pl",
                    "bsbr.pl",
                    "bsbransk.pl",
                    "bsbrzeg.pl",
                    "bsbrzeznica.pl",
                    "bsbuskozdroj.pl",
                    "bschmielnik.pl",
                    "bschojnice.pl",
                    "bschrzanow.pl",
                    "bsciechanowiec.pl",
                    "bscycow.pl",
                    "bsczarnydunajec.pl",
                    "bsczechowice.com.pl",
                    "bsczyzew.pl",
                    "bsdabrowatarnowska.pl",
                    "bsdaleszyce-gorno.pl",
                    "bsdobczyce.pl",
                    "bsdobrzen.pl",
                    "bsdynow.pl",
                    "bselk.pl",
                    "bsframpol.pl",
                    "bsgarwolin.com.pl",
                    "bsgliwice.pl",
                    "bsgliwice24.pl",
                    "bsglogow.pl",
                    "bsglogowmlp.pl",
                    "bsgogolin.online",
                    "bsgogolin.pl",
                    "bsgostynin.pl",
                    "bsgoworowo.pl",
                    "bsgrodkow.pl",
                    "bsgrybow.pl",
                    "bshajnowka.pl",
                    "bsilowa.pl",
                    "bsj24.pl",
                    "bsjablonka.pl",
                    "bsjaroslaw.pl",
                    "bsjasienica.pl",
                    "bsjasieniec.pl",
                    "bsjasionka.pl",
                    "bsjastrzebie.pl",
                    "bsjawor.pl",
                    "bsjaworzno.pl",
                    "bsjedwabne.pl",
                    "bsjelesnia.pl",
                    "bsjordanow.pl",
                    "bsjozefow.pl",
                    "bsjuchnowiec.pl",
                    "bskadzidlo.pl",
                    "bskaluszyn.pl",
                    "bskamgora.pl",
                    "bskamien.pl",
                    "bskarczew.pl",
                    "bskazimierzdolny.pl",
                    "bskielce.com.pl",
                    "bsklobuck.pl",
                    "bsklodzko.pl",
                    "bskock.pl",
                    "bskolaczyce.pl",
                    "bskolno.pl",
                    "bskonopiska.pl",
                    "bskonskowola.pl",
                    "bskornica.pl",
                    "bskorycin.pl",
                    "bskoszecin.com.pl",
                    "bskoszecin.pl",
                    "bskozuchow.pl",
                    "bskrapkowice.pl",
                    "bskrasnik.pl",
                    "bskrasnosielc.pl",
                    "bskrasnystaw.pl",
                    "bskrzyzanowice.pl",
                    "bsksiezpol.pl",
                    "bskw.pl",
                    "bslacko.pl",
                    "bslancut.pl",
                    "bslapy.pl",
                    "bslaszczow.pl",
                    "bsleczna.pl",
                    "bslegionowo.pl",
                    "bslegnica.pl",
                    "bslesnica.pl",
                    "bslesniowice.pl",
                    "bslezajsk.pl",
                    "bslochow.pl",
                    "bslomazy.pl",
                    "bslomza.pl",
                    "bslopuszno.pl",
                    "bslosice.pl",
                    "bslososinadolna.pl",
                    "bslubaczow.pl",
                    "bslubartow.pl",
                    "bslubawa.pl",
                    "bslubenia.pl",
                    "bslubniany.pl",
                    "bslukow.pl",
                    "bsmalawies.pl",
                    "bsmiedzna.pl",
                    "bsmiedzyrzec.pl",
                    "bsmilicz.com.pl",
                    "bsminskmaz.pl",
                    "bsmonki.pl",
                    "bsmragowo.pl",
                    "bsmrozy.pl",
                    "bsmstow.pl",
                    "bsmszana.pl",
                    "bsmuszyna.pl",
                    "bsmykanow.pl",
                    "bsmyszkow.pl",
                    "bsnaleczow.pl",
                    "bsnamyslow.com.pl",
                    "bsnarew.pl",
                    "bsnarol.pl",
                    "bsndm.pl",
                    "bsniechobrz.pl",
                    "bsniedrzwicaduza.pl",
                    "bsnielisz.pl",
                    "bsniemce.pl",
                    "bsnowasol.pl",
                    "bsnowysacz.pl",
                    "bsnowytarg.pl",
                    "bsobsza.pl",
                    "bsolecko.pl",
                    "bsolesnica.net",
                    "bsolesnica.pl",
                    "bsolsztynek.pl",
                    "bsostrowmaz.pl",
                    "bsotmuchow.pl",
                    "bsotwock.pl",
                    "bspajeczno.pl",
                    "bspawlowice.pl",
                    "bspiaseczno.pl",
                    "bspiensk.pl",
                    "bspilzno.pl",
                    "bspinczow.pl",
                    "bsplonsk.pl",
                    "bspoczesna.pl",
                    "bspoddebice.pl",
                    "bspodegrodzie.pl",
                    "bspolaniec.pl",
                    "bsponiatowa.pl",
                    "bspopow.pl",
                    "bsporabka.pl",
                    "bsproszowice.com.pl",
                    "bsprudnik.pl",
                    "bsprzasnysz.pl",
                    "bspszczyna.pl",
                    "bsradom.com.pl",
                    "bsradom.pl",
                    "bsradomyslwielki.com.pl",
                    "bsradomyslwielki.pl",
                    "bsradzyn.pl",
                    "bsradzyn24.pl",
                    "bsrajcza.pl",
                    "bsraszyn.pl",
                    "bsropczyce.pl",
                    "bsrozan.pl",
                    "bsryki.pl",
                    "bsryki24.pl",
                    "bsrymanow.pl",
                    "bssedziszow.pl",
                    "bssejny.pl",
                    "bssiedlce.pl",
                    "bssiemiatycze.pl",
                    "bsskierniewice.pl",
                    "bssobienie.pl",
                    "bssobieniejeziory.pl",
                    "bssochaczew.pl",
                    "bssokolow.pl",
                    "bssrodasl.pl",
                    "bsstarachowice.pl",
                    "bsstarozreby.pl",
                    "bsstarysacz.pl",
                    "bsstrzyzow.pl",
                    "bssucha.pl",
                    "bssuwalki.pl",
                    "bsswidnica.pl",
                    "bsszczekociny.pl",
                    "bsszczucin.malopolska.info",
                    "bsszczucin.pl",
                    "bsszczuczyn.pl",
                    "bsszczytno.pl",
                    "bstarczyn.pl",
                    "bstarnobrzeg.pl",
                    "bstarnogrod.pl",
                    "bstg.pl",
                    "bstomaszowl.pl",
                    "bstrzebiel.pl",
                    "bstrzebnica.pl",
                    "bstworog.pl",
                    "bstychy.com.pl",
                    "bstyczyn.pl",
                    "bswachock.pl",
                    "bswasewo.pl",
                    "bswielopole.pl",
                    "bswilamowice.pl",
                    "bszagan.pl",
                    "bszakopane.pl",
                    "bszambrow.pl",
                    "bszbuczyn.pl",
                    "bszgierz.pl",
                    "bszmigrod.com.pl",
                    "bszolynia.pl",
                    "bszory.pl",
                    "bszyrakow.pl",
                    "cui.pl",
                    "dmbps.pl",
                    "e-bskozuchow.pl",
                    "e-bspszczyna.pl",
                    "e-bsw.pl",
                    "e-gbsradkow.pl",
                    "e25.pl",
                    "ebankbsilawa.pl",
                    "ebankbszam.pl",
                    "ebo24.pl",
                    "ebs-zabkowicesl.pl",
                    "ebskazimierzdolny.pl",
                    "etnobank.pl",
                    "gbsbank.pl",
                    "gbsradkow.pl",
                    "hexabank.pl",
                    "kartosfera.pl",
                    "kbsmyszyniec.pl",
                    "loginbsustron.pl",
                    "lomianki.com.pl",
                    "lubelskibs.pl",
                    "mazoviabank.pl",
                    "mbsbank.pl",
                    "mbsgizycko.pl",
                    "mbsw.pl",
                    "nbs24.pl",
                    "nbsbank.pl",
                    "nbscorponet.pl",
                    "nbspulawy.pl",
                    "okbank.pl",
                    "pbs.zamosc.pl",
                    "pbskkozle.pl",
                    "pbsknyszyn.pl",
                    "pbsopolelubelskie.pl",
                    "pbssokolow.pl",
                    "pbswegrow.pl",
                    "pbszlotoryja.pl",
                    "pmbank.pl",
                    "powislanski.pl",
                    "psbank.pl",
                    "rbsbychawa.pl",
                    "rbsrybnik.pl",
                    "sanbank.pl",
                    "sbppiaski.pl",
                    "sbrbank.pl",
                    "silesiabank.pl",
                    "tatrzanskibs.pl",
                    "wbs-bank.pl",
                    "wbs-jonkowo.pl",
                    "wmbs.pl",
                ]
            },
            {
                name: "GünayBank",
                domains:
                [
                    "gunaybank.com",
                    "gunaybank.az",
                ]
            },
            {
                name: "Haitong",
                domains:
                [
                    "haitongib.com",
                ]
            },
            {
                name: "Hello bank",
                domains:
                [
                    "hellobank.at",
                ]
            },
            {
                name: "HSBC",
                domains:
                [
                    "hangseng.com",
                    "hsbc.ae",
                    "hsbc.am",
                    "hsbc.bm",
                    "hsbc.ca",
                    "hsbc.ch",
                    "hsbc.cl",
                    "hsbc.co.id",
                    "hsbc.co.il",
                    "hsbc.co.in",
                    "hsbc.co.jp",
                    "hsbc.co.kr",
                    "hsbc.co.mu",
                    "hsbc.co.nz",
                    "hsbc.co.om",
                    "hsbc.co.th",
                    "hsbc.co.uk",
                    "hsbc.co.za",
                    "hsbc.com",
                    "hsbc.com.ar",
                    "hsbc.com.au",
                    "hsbc.com.bd",
                    "hsbc.com.bh",
                    "hsbc.com.bn",
                    "hsbc.com.cn",
                    "hsbc.com.eg",
                    "hsbc.com.hk",
                    "hsbc.com.kw",
                    "hsbc.com.lb",
                    "hsbc.com.mo",
                    "hsbc.com.mt",
                    "hsbc.com.mx",
                    "hsbc.com.my",
                    "hsbc.com.ph",
                    "hsbc.com.qa",
                    "hsbc.com.sg",
                    "hsbc.com.tr",
                    "hsbc.com.tw",
                    "hsbc.com.uy",
                    "hsbc.com.vn",
                    "hsbc.cz",
                    "hsbc.de",
                    "hsbc.es",
                    "hsbc.fr",
                    "hsbc.gr",
                    "hsbc.jo",
                    "hsbc.ie",
                    "hsbc.lk",
                    "hsbc.pl",
                    "hsbcnet.com",
                    "hsbcprivatebank.com",
                    "hsbcsaudi.com",
                    "sabb.com",
                    "sabbnet.com",
                ]
            },
            {
                name: "ICBC - Industrial and Commercial Bank of China",
                domains:
                [
                    "icbc.com.cn",
                    "icbc-ltd.com",
                ]
            },
            {
                name: "IDBank",
                domains:
                [
                    "idbank.am",
                ]
            },
            {
                name: "Idea Bank",
                domains:
                [
                    "ideabank.by",
                    "ideabank24.by",
                    "ideabank.pl",
                ]
            },
            {
                name: "Ikano Bank",
                domains:
                [
                    "bank.ikano",
                    "ikano.co.uk",
                    "ikano.dk",
                    "ikano.no",
                    "ikano-storeportal.de",
                    "ikano-storeportal.pl",
                    "ikanobank.at",
                    "ikanobank.de",
                    "ikanobank.dk",
                    "ikanobank.fi",
                    "ikanobank.no",
                    "ikanobank.ru",
                    "ikanobank.se",
                    "my.ikano",
                    "onlinebanking.ikea-kreditkarte.de",
                    "onlinebanking-ikanobank.de",
                    "portalbank.dk",
                ]
            },
            {
                name: "Inbank",
                domains:
                [
                    "inbankpolska.pl",
                ]
            },
            {
                name: "INECOBANK",
                domains:
                [
                    "inecobank.am",
                ]
            },
            {
                name: "ING",
                domains:
                [
                    "ing.be",
                    "ing.pl",
                    "ingbank.pl",
                    "inghipoteczny.pl",
                ]
            },
            {
                name: "Intesa Sanpaolo",
                domains:
                [
                    "alexbank.com",
                    "banca5.com",
                    "bankain.si",
                    "bancaintesa.rs",
                    "bancaintesa.ru",
                    "cib.hu",
                    "epsilonsgr.it",
                    "eurizoncapital.com",
                    "eurizoncapital.it",
                    "eurizonslovakia.com",
                    "eximbank.com",
                    "eximbank.md",
                    "fideuram.it",
                    "fideuramgestions.lu",
                    "fideuramireland.ie",
                    "fideuramonline.it",
                    "fideuramvita.it",
                    "intesasanpaolo.com",
                    "intesasanpaoloassicura.com",
                    "intesasanpaolobank.al",
                    "intesasanpaolobank.ro",
                    "intesasanpaolobank.si",
                    "intesasanpaolobanka.ba",
                    "intesasanpaolobankireland.ie",
                    "intesasanpaolobankluxembourg.lu",
                    "intesasanpaolobrasil.com.br",
                    "intesasanpaolopbmorval.ch",
                    "intesasanpaoloprivatebanking.com",
                    "intesasanpaoloprivatebanking.it",
                    "intesasanpaoloprivatebanksuisse.ch",
                    "intesasanpaolovita.it",
                    "pbz.hr",
                    "pravex.com.ua",
                    "pravex.ua",
                    "sirefiduciaria.it",
                    "vub.sk",
                ]
            },
            {
                name: "John Deere Bank",
                domains:
                [
                    "deere.com",
                    "deere.pl",
                ]
            },
            {
                name: "J.P. Morgan",
                domains:
                [
                    "chase.com",
                    "jpmorgan.com",
                    "paymentech.net",
                ]
            },
            {
                name: "Kathrein Privatbank",
                domains:
                [
                    "kathrein.at",
                ]
            },
            {
                name: "KBC",
                domains:
                [
                    "add.be",
                    "cbc.be",
                    "claim.bg",
                    "csob.cz",
                    "csob.sk",
                    "csobam.cz",
                    "csobleasing.cz",
                    "csobleasing.sk",
                    "csobpoj.cz",
                    "dzi.bg",
                    "insurance-architects.be",
                    "kbc.be",
                    "kbc.com",
                    "kbc.ie",
                    "kbc-group.com",
                    "kbc2s.com",
                    "kbcbrussels.be",
                    "kbcgroupre.lu",
                    "kbclease.lu",
                    "kbcsecurities.com",
                    "kh.hu",
                    "khdirektbiztositas.hu",
                    "origamirisk.com",
                    "ubb.bg",
                    "vab.be",
                ]
            },
            {
                name: "Kommunal Kredit",
                domains:
                [
                    "kommunalkredit.at",
                    "kommunalkreditdirekt.at",
                ]
            },
            {
                name: "KredoBank",
                domains:
                [
                    "kredobank.com.ua",
                ]
            },
            {
                name: "Keytrade Bank",
                domains:
                [
                    "keytradebank.be",
                ]
            },
            {
                name: "LGT - Private Banking and Asset Management",
                domains:
                [
                    "lgt.at",
                    "lgt.ch",
                    "lgt.com",
                    "lgt.li",
                    "lgtcp.com",
                    "lgtvestra.com",
                    "navconsulting.net",
                ]
            },
            {
                name: "Liechtensteinische Landesbank",
                domains:
                [
                    "llb.at",
                ]
            },
            {
                name: "mBank",
                domains:
                [
                    "kompaktfinanse.pl",
                    "mbank.pl",
                    "mhipoteczny.pl",
                ]
            },
            {
                name: "MeDirect",
                domains:
                [
                    "medirect.be",
                    "medirect.com.mt",
                ]
            },
            {
                name: "Mercedes-Benz Bank",
                domains:
                [
                    "mercedes-benz.com",
                    "mercedes-benz.pl",
                ]
            },
            {
                name: "MONETA Money Bank",
                domains:
                [
                    "internetbanka.cz",
                    "moneta.cz",
                ]
            },
            {
                name: "MORABANC",
                domains:
                [
                    "morabanc.ad",
                ]
            },
            {
                name: "МТБанк (MTBank)",
                domains:
                [
                    "mtbank.by",
                    "mybank.by",
                ]
            },
            {
                name: "MUFG Bank",
                domains:
                [
                    "bankmufg.pl",
                    "mufg.jp",
                ]
            },
            {
                name: "MuganBank",
                domains:
                [
                    "muganbank.az",
                ]
            },
            {
                name: "NBC",
                domains:
                [
                    "bnc.ca",
                    "nbc.bank",
                    "nbc.ca",
                    "secure-nbcok.com",
                    "secureinternetbank.com",
                    "thenbcbank.com",
                ]
            },
            {
                name: "Nest Bank",
                domains:
                [
                    "nestbank.pl",
                ]
            },
            {
                name: "Noble Bank",
                domains:
                [
                    "noblebank.pl",
                    "noblesecurities.pl",
                ]
            },
            {
                name: "Nordea",
                domains:
                [
                    "nordea.com",
                ]
            },
            {
                name: "Nykredit",
                domains:
                [
                    "nykredit.com",
                    "nykredit.dk",
                ]
            },
            {
                name: "Oberbank",
                domains:
                [
                    "banking-oberbank.at",
                    "oberbank.com",
                ]
            },
            {
                name: "Parabokt",
                domains:
                [
                    "parabank.az",
                    "parabokt.az",
                ]
            },
            {
                name: "МТБанк (Paritetbank)",
                domains:
                [
                    "paritetbank.by",
                ]
            },
            {
                name: "PASHA Bank",
                domains:
                [
                    "pashabank.az",
                    "pashabank.digital",
                ]
            },
            {
                name: "PKO Bank Polski S.A.",
                domains:
                [
                    "inteligo.pl",
                    "ipko.pl",
                    "pkobh.pl",
                    "pkobp.pl",
                ]
            },
            {
                name: "Plus Bank",
                domains:
                [
                    "plusbank.pl",
                    "plusbank24.pl",
                ]
            },
            {
                name: "Premium Bank",
                domains:
                [
                    "premiumbank.az",
                ]
            },
            {
                name: "ProCredit Bank",
                domains:
                [
                    "procreditbank.com.al",
                ]
            },
            {
                name: "BANQUE PSA FINANCE S.A.",
                domains:
                [
                    "e-psafinance.pl",
                ]
            },
            {
                name: "Puilaetco",
                domains:
                [
                    "puilaetco.be",
                ]
            },
            {
                name: "Rabobank",
                domains:
                [
                    "rabobank.be",
                    "rabobank.com",
                    "rabobank.nl",
                    "rabotransactasiav5.com",
                ]
            },
             {
                name: "Raiffeisen Bank International",
                domains:
                [
                    "custody.a",
                    "myraiffeisen.com",
                    "priorbank.by",
                    "raiffeisen.al",
                    "raiffeisen.at",
                    "raiffeisen.it",
                    "rbinternational.com",
                    "rbinternational.com.pl",
                    "raiffeisenresearch.com",
                    "rcb.at",
                    "rcm.at",
                    "yellowe.com",
                ]
            },
            {
                name: "RCI Banque S.A.",
                domains:
                [
                    "daciafinansowanie.pl",
                    "nissanfinance.pl",
                    "rcibanque.com",
                    "rcibanque.com.pl",
                    "rcibs.com",
                    "renaultfinansowanie.pl",
                ]
            },
            {
                name: "Santander",
                domains:
                [
                    "centrum24.pl",
                    "ibiznes24.pl",
                    "inwestoronline.pl",
                    "monsantanderconsumerfinance.be",
                    "santander.be",
                    "santander.com",
                    "santander.pl",
                    "santandercib.com",
                    "santanderconsumer.pl",
                ]
            },
            {
                name: "S|E|B",
                domains:
                [
                    "seb.de",
                    "seb.ee",
                    "seb.lt",
                    "seb.lv",
                    "seb.pl",
                    "seb.se",
                    "sebank.se",
                    "sebgroup.com",
                ]
            },
            {
                name: "Semper Constantia",
                domains:
                [
                    "sc-immo.at",
                    "semperconstantia.at",
                ]
            },
            {
                name: "SGB Bank S.A.",
                domains:
                [
                    "bank-kaszubski.pl",
                    "bankblaszki.pl",
                    "bankrumia.pl",
                    "banksiedlec.pl",
                    "bbs-bank.pl",
                    "bs.bialystok.pl",
                    "bs.gniezno.pl",
                    "bs.olawa.pl",
                    "bs-belchatow.com.pl",
                    "bs-glowno.com.pl",
                    "bs-glowno.eu",
                    "bs-glowno.pl",
                    "bs-malbork.com.pl",
                    "bs-malbork.pl",
                    "bs-starogard.pl",
                    "bs-swiecie.pl",
                    "bs-zwolen.com.pl",
                    "bs24gniezno.pl",
                    "bs24slupca.pl",
                    "bsbd.pl",
                    "bsbd24.pl",
                    "bsbiala.com.pl",
                    "bsbialobrzegi.pl",
                    "bsbialogard.pl",
                    "bsbiezun.pl",
                    "bsbytow.com.pl",
                    "bschodziez.pl",
                    "bschojna.pl",
                    "bschynow.pl",
                    "bsczarnkow.pl",
                    "bsczersk.pl",
                    "bsczluchow.pl",
                    "bsdobrzyca.pl",
                    "bsduszniki.pl",
                    "bsdzialdowo.pl",
                    "bsdzierzgon.pl",
                    "bsdzierzoniow.pl",
                    "bsgabin.pl",
                    "bsglinojeck.pl",
                    "bsglowaczow.pl",
                    "bsgniew.pl",
                    "bsgoleniow.pl",
                    "bsgolub24.pl",
                    "bsgolubdobrzyn.pl",
                    "bsgora.pl",
                    "bsgrabow.pl",
                    "bsgrebocin.pl",
                    "bsgrodzisk.pl",
                    "bsgrojec.pl",
                    "bsgrudusk.pl",
                    "bsgryfice.pl",
                    "bsgryfino.pl",
                    "bshalinow.pl",
                    "bsilow.pl",
                    "bsinowroclaw.pl",
                    "bsjarocin.pl",
                    "bsjastrowie.pl",
                    "bsjedlinsk.pl",
                    "bsjutrosin.pl",
                    "bskaliszpom.pl",
                    "bskcynia.pl",
                    "bskleszczow.pl",
                    "bsklodawa.eu",
                    "bskobierzyce.pl",
                    "bskonin.pl",
                    "bskoronowo.com.pl",
                    "bskoscian.pl",
                    "bskoscierzyna.pl",
                    "bskostrzyn.pl",
                    "bskowal.pl",
                    "bskowalewo.pl",
                    "bskrokowa.pl",
                    "bskrosniewice.com.pl",
                    "bskrosno.pl",
                    "bskrotoszyn.pl",
                    "bskruszwica.pl",
                    "bskutno.pl",
                    "bslasin.pl",
                    "bsleba.pl",
                    "bsleczyca.pl",
                    "bslipka.pl",
                    "bslipno.pl",
                    "bslipsko.pl",
                    "bslubichowo.com",
                    "bslubraniec.pl",
                    "bslubycza.pl",
                    "bslwowekslaski.pl",
                    "bsmazowsze.pl",
                    "bsmlawa.pl",
                    "bsmszczonow.pl",
                    "bsnaklo.pl",
                    "bsnasielsk.pl",
                    "bsnowe.com.pl",
                    "bsnowystaw.pl",
                    "bsnowytomysl.pl",
                    "bsopoczno.pl",
                    "bsosie.pl",
                    "bsosno.pl",
                    "bsozarow.pl",
                    "bspaluki.pl",
                    "bspaslek.pl",
                    "bspionki.pl",
                    "bspk.pl",
                    "bspleszew.pl",
                    "bspolczyn.pl",
                    "bsponiec.pl",
                    "bsprabuty.pl",
                    "bspruszcz.pl",
                    "bspruszczgd.pl",
                    "bsprzedborz.pl",
                    "bsprzysucha.pl",
                    "bspszczolki.pl",
                    "bspuck.pl",
                    "bspultusk.pl",
                    "bsraciaz.pl",
                    "bsraszkow.com.pl",
                    "bsraszkow.pl",
                    "bsrusiec.pl",
                    "bsrz.pl",
                    "bsrzepin.pl",
                    "bssandomierz.com.pl",
                    "bssantok.pl",
                    "bssieradz.pl",
                    "bssierakow.pl",
                    "bssierakowice.pl",
                    "bsskaryszew.pl",
                    "bsslawno.pl",
                    "bsslesin.pl",
                    "bsslupca.pl",
                    "bssmigiel.pl",
                    "bssokoly.pl",
                    "bssrodawlkp.pl",
                    "bsstarabiala.pl",
                    "bsstegna.pl",
                    "bsstrykow.pl",
                    "bsstrzegowo.pl",
                    "bssusz.pl",
                    "bsszadek.pl",
                    "bssztum.pl",
                    "bsszubin.pl",
                    "bstczew.pl",
                    "bsteresin.pl",
                    "bstorun.pl",
                    "bstorun24.pl",
                    "bstuchola.pl",
                    "bsustka.pl",                    
                    "bswarka.com.pl",
                    "bswarka.pl",
                    "bswartkowice.pl",
                    "bswiecbork.pl",
                    "bswielen.pl",
                    "bswierzbinek.com.pl",
                    "bswierzbinek.pl",
                    "bswiskitki.pl",
                    "bswitkowo.pl",
                    "bswloszakowice.pl",
                    "bswolczyn.pl",
                    "bswolczyn24.pl",
                    "bswolin.pl",
                    "bswronki.pl",
                    "bswschowa.pl",
                    "bswschowa24.pl",
                    "bsziemikal.pl",
                    "bszl.com.pl",
                    "bszl.pl",
                    "bszp.pl",
                    "bszuromin.pl",
                    "bszw.pl",                    
                    "ebsd.pl",
                    "esbank.pl",
                    "expressbank.pl",
                    "gbs.net.pl",
                    "gbschoszczno.pl",
                    "gbsmosina.pl",
                    "gbsstrzelin.pl",
                    "inobanknet.pl",
                    "k-gbs.pl",
                    "kbs-bank.pl",
                    "kdbs.com.pl",
                    "lbsoborniki.pl",
                    "lbsstrzalkowo.pl",
                    "lbszdwola.pl",
                    "lodzkibs.pl",
                    "lubuskibs.pl",
                    "lwbsdrezdenko.pl",
                    "nadnoteckibank.pl",
                    "naszbank.pl",
                    "nbs-rakoniewice.pl",
                    "nbsdzialoszyn.pl",
                    "nbsrakoniewice.pl",
                    "net-bank.com.pl",
                    "nicolausbank24.pl",
                    "pacobank.pl",
                    "paluckibs.pl",                 
                    "pbs.poznan.pl",
                    "pbsgostyn.pl",
                    "pbstom.com.pl",
                    "pbswrzesnia.com.pl",
                    "pbswrzesnia.pl",
                    "piastowskibs.com.pl",
                    "pomorski-bs.pl",
                    "psbspyrzyce.pl",
                    "rbs.lututow.pl",
                    "sblkepno.pl",
                    "sblskalmierzyce.com.pl",
                    "sblskalmierzyce.pl",
                    "sblsrem.pl",
                    "sblzakrzewo.pl",
                    "sblzlotow.com.pl",
                    "sgb.pl",
                    "sgb24.pl",
                    "zulawskibs.pl",
                ]
            },
            {
                name: "Société Générale",
                domains:
                [
                    "kleinworthambros.com",
                    "sgbt.lu",
                    "societegenerale.al",
                    "societegenerale.ch",
                    "societegenerale.com",
                    "societegenerale.fr",
                    "societegenerale.mc",
                    "societegenerale.pl",
                    "sgmarkets.com",
                ]
            },
            {
                name: "Sparbanken Skåne AB",
                domains:
                [
                    "sparbankenskane.se",
                    "swedbank.se",
                ]
            },
            {
                name: "Sparda-Bank",
                domains:
                [
                    "sparda.at",
                    "sparda.de",
                    "sparda-a.de",
                    "sparda-b.de",
                    "sparda-bank-hamburg.de",
                    "sparda-bw.de",
                    "sparda-h.de",
                    "sparda-hessen.de",
                    "sparda-m.de",
                    "sparda-n.de",
                    "sparda-ostbayern.de",
                    "sparda-sw.de",
                    "sparda-verband.de",
                    "sparda-west.de",
                    "spardawien.at",
                    "goteo.de",
                ]
            },
            {
                name: "Svenska Handelsbanken AB",
                domains:
                [
                    "edb.com",
                    "handelsbanken.com",
                    "handelsbanken.dk",
                    "handelsbanken.fi",
                    "handelsbanken.nl",
                    "handelsbanken.no",
                    "handelsbanken.se",
                    "nets.no",
                    "shb.dk",
                ]
            },
            {
                name: "Texnikabank",
                domains:
                [
                    "texnikabank.com",
                ]
            },
            {
                name: "Технобанк (Tehnobank)",
                domains:
                [
                    "tb.by",
                ]
            },
            {
                name: "TF Bank",
                domains:
                [
                    "tfbank.fi",
                    "tfbank.pl",
                    "tfbankgroup.com",
                ]
            },
            {
                name: "Tirana Bank",
                domains:
                [
                    "tiranabank.al",
                ]
            },
            {
                name: "ТК Банк (TK Bank)",
                domains:
                [
                    "tcbank.by",
                ]
            },
            {
                name: "Toyota Bank",
                domains:
                [
                    "toyotabank.pl",
                    "toyotaleasing.pl",
                ]
            },
            {
                name: "Triodos Bank",
                domains:
                [
                    "triodos.be",
                    "triodos.co.uk",
                    "triodos.com",
                    "triodos.de",
                    "triodos.es",
                    "triodos.fr",
                    "triodos.nl",
                ]
            },
            {
                name: "Turan Bank",
                domains:
                [
                    "turanbank.az",
                ]
            },
            {
                name: "Turon Bank",
                domains:
                [
                    "turonbank.uz",
                ]
            },
            {
                name: "UBS Group AG",
                domains:
                [
                    "ubs.com",
                ]
            },
            {
                name: "Unibank",
                domains:
                [
                    "unibank.am",
                    "unibank.az",
                    "unibank.com",
                ]
            },
            {
                name: "UniCredit",
                domains:
                [
                    "bankaustria.at",
                    "bulbank.bg",
                    "bulbankonline.bg",
                    "hypovereinsbank.de",
                    "schoellerbank.at",
                    "unicredit.eu",
                    "unicredit.it",
                    "unicredit.ru",
                    "unicreditbanking.eu",
                    "unicreditbanking.net",
                    "unicreditgroup.eu",
                    "unicreditleasing.hr",
                    "zaba.hr",
                ]
            },
            {
                name: "UNIONBANK",
                domains:
                [
                    "unionbank.al",
                ]
            },
            {
                name: "United Bank of Albania",
                domains:
                [
                    "uba.com.al",
                ]
            },
            {
                name: "VakifBank",
                domains:
                [
                    "onlinebanking-vakif-bank.de",
                    "vakif-bank.de",
                    "vakifbank.at",
                    "vakifbank.com.tr",
                    "vakifbankusa.com",
                ]
            },
            {
                name: "Vallback",
                domains:
                [
                    "vallbanc.ad",
                ]
            },
            {
                name: "Van Lanschot",
                domains:
                [
                    "vanlanschot.be",
                    "vanlanschot.com",
                ]
            },
            {
                name: "VDK",
                domains:
                [
                    "vdk.be",
                ]
            },
            {
                name: "VKB|Bank",
                domains:
                [
                    "vkb-bank.at",
                ]
            },
            {
                name: "Volksbank",
                domains:
                [
                    "volksbank.at",
                ]
            },
            {
                name: "Vontobel",
                domains:
                [
                    "deritrade.com",
                    "vontobel.com",
                ]
            },
            {
                name: "VTB",
                domains:
                [
                    "vtb.am",
                    "vtb.com",
                    "vtb.ru",
                    "vtbcapital.com",
                    "vtbcapital.ru",
                ]
            },
            {
                name: "Volkswagen Bank",
                domains:
                [
                    "autoaukcja.com",
                    "vwbank.pl",
                    "vwfs.pl",
                    "vwleasing.pl",
                ]
            },
            {
                name: "Wiener Privatbank",
                domains:
                [
                    "fundmanager-pro.com",
                    "wienerprivatbank.com",
                ]
            },
            {
                name: "Xalq Bank",
                domains:
                [
                    "xalqbank.az",
                    "xalqonline.az",
                ]
            },
            {
                name: "Yapi Kredi Bank Azərbaycan",
                domains:
                [
                    "yapikredi.com.az",
                ]
            },
            {
                name: "Yelo Bank",
                domains:
                [
                    "yelo.az",
                ]
            },
            {
                name: "Zepterbank",
                domains:
                [
                    "zepterbank.by",
                ]
            },
            {
                name: "Zürcher Kantonalbank Österreich AG",
                domains:
                [
                    "zkb-oe.at",
                ]
            },        
        ]
    },
    {
        name: "payment", 
        icon: "/img/category/payment/default.png",
        groups: 
        [
            {
                name: "Elavon",
                domains:
                [
                    "elavon.pl",
                    "elavonconnect.com",
                    "elavonpayment.com",                
                ]
            },
            {
                name: "Western Union",
                domains:
                [
                    "westernunion.com",
                ]
            },
        ]
    },
];
